### PR TITLE
Update HawkTracer to 0.10.0

### PR DESCRIPTION
**Pull request by loganek**
Also a few more fixes:
 * use new API for creating and registering listeners (HawkTracer now can manage lifetime of the listeners)
 * fix CI build by removing pkg-config feature (it would only work if we installed hawktracer in the CI as well)

### CODE REVIEW

**Comment by loganek** [comment]
Just wondering; what's the value of having `pregenerated_bindings.rs` file? Can we always generate the bindings file instead?

**Comment by AlexEne** [comment]
No, I like providing some default ones just to avoid making people install LLVM (that's not pleasant on Windows for example).

**Comment by AlexEne** [comment]
Is it ok if you bump the version in `cargo.toml` as well?

**Comment by loganek** [comment]
> Is it ok if you bump the version in `cargo.toml` as well?

Yes, if you think it's time to do the new release, then yes. I didn't do that because I thought you might want to include more changes in this release.

**Comment by AlexEne** [comment]
Thanks for this :D

**Pull request merged**
